# -*- coding: utf-8 -*-
"""atms..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8mgS4ALG2TJddl_dWmdcVWeS-LAI_Km
"""

# All necessary packages should be listed in a 'requirements.txt' file for Streamlit deployment.

from googleapiclient.discovery import build
import pandas as pd
import re
import networkx as nx
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

pip install google-api-python-client pandas networkx scikit-learn

import requests

API_KEY = "AIzaSyDYP-2xVmDPdcyHZ6si_eypeQhP4l7WBag"

url = "https://maps.googleapis.com/maps/api/place/textsearch/json"

params = {
    "query": "Candi Borobudur",
    "key": "AIzaSyDYP-2xVmDPdcyHZ6si_eypeQhP4l7WBag"
}

res = requests.get(url, params=params)
data = res.json()

place_id = data["results"][0]["place_id"]
print(place_id)

def get_reviews(place_id, place_name):

    url = "https://maps.googleapis.com/maps/api/place/details/json"

    params = {
        "place_id": place_id,
        "fields": "name,rating,reviews",
        "key": "AIzaSyDYP-2xVmDPdcyHZ6si_eypeQhP4l7WBag"
    }

    res = requests.get(url, params=params)

    data = res.json()

    reviews=[]

    for r in data.get("result",{}).get("reviews",[]):

        reviews.append({

            "place":place_name,

            "rating":r.get("rating"),

            "comment":r.get("text")
        })

    return reviews

def get_place_id(query):
    url = "https://maps.googleapis.com/maps/api/place/textsearch/json"
    params = {
        "query": query,
        "key": API_KEY # API_KEY is defined globally
    }
    res = requests.get(url, params=params)
    data = res.json()
    if data and data.get("results"):
        return data["results"][0]["place_id"]
    return None

all_data=[]

places = [
    "Candi Borobudur",
    "Candi Prambanan",
    "Gunung Bromo",
    "Malioboro",
    "Raja Ampat",
    "Labuan Bajo",
    "Danau Toba",
    "Pantai Kuta Bali",
    "Pantai Parangtritis",
    "Kawah Ijen",
    "Monas Jakarta",
    "Taman Mini Indonesia Indah",
    "Tangkuban Perahu",
    "Pantai Sanur Bali",
    "Bali Zoo",
    "Jatim Park 1",
    "Jatim Park 2",
    "Museum Angkut",
    "Pantai Pangandaran",
    "Kebun Raya Bogor"
] # Define the 'places' variable with the desired locations

for p in places:

    print("Processing:",p)

    pid=get_place_id(p)

    if pid:

        review=get_reviews(pid,p)

        all_data.extend(review)

import pandas as pd

df=pd.DataFrame(all_data)

print(df.head())

print(df.shape)

df.to_csv("wisata_dataset.csv",index=False)

"""preprocecing"""

pip install Sastrawi

import re

def clean_text(text):

    text=str(text)

    text=text.lower()

    text=re.sub(r"http\S+","",text)

    text=re.sub(r"[^a-zA-Z\s]","",text)

    text=re.sub(r"\s+"," ",text)

    return text.strip()

df["clean_comment"]=df["comment"].apply(clean_text)

df[["comment","clean_comment"]].head()

def label_rating(r):

    if r==5:

        return "Puas"

    elif r<=2:

        return "Kecewa"

    else:

        return None

df["label"]=df["rating"].apply(label_rating)

df=df.dropna()

"""TF IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

X=tfidf.fit_transform(df["clean_comment"])

y=df["label"]

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

model.fit(X_train,y_train)

print(model.score(X_test,y_test))

from sklearn.cluster import KMeans

kmeans=KMeans(

    n_clusters=3,

    random_state=42
)

cluster=kmeans.fit_predict(X)

df["cluster"]=cluster

df[["clean_comment","cluster"]].head()

from collections import Counter

all_words=" ".join(df["clean_comment"])

Counter(all_words.split()).most_common(20)

pip install wordcloud

from wordcloud import WordCloud

import matplotlib.pyplot as plt

text=" ".join(df["clean_comment"])

wc=WordCloud(

width=800,

height=400

).generate(text)

plt.figure(figsize=(12,5))

plt.imshow(wc)

plt.axis("off")

plt.show()

pip install networkx

import networkx as nx

G=nx.Graph()

places=df["place"].unique()

for p in places:

    G.add_node(p)

for i in range(len(places)-1):

    G.add_edge(

        places[i],

        places[i+1]
    )

import matplotlib.pyplot as plt

plt.figure(figsize=(10,7))

nx.draw(

    G,

    with_labels=True,

    node_size=3000,

    font_size=10
)

plt.show()

df.to_csv(
    "hasil_akhir_wisata.csv",
    index=False
)

"""## Analisis Rating Tempat Wisata"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate average rating per place
avg_ratings = df.groupby('place')['rating'].mean().sort_values(ascending=False)

# Get top 5 highest rated places
top_5_places = avg_ratings.head(5)

# Get top 5 lowest rated places
bottom_5_places = avg_ratings.tail(5).sort_values(ascending=True)

# Combine for plotting
plot_data = pd.concat([top_5_places, bottom_5_places])

plt.figure(figsize=(12, 6))
sns.barplot(x=plot_data.index, y=plot_data.values, palette='viridis')
plt.title('Top 5 Highest and Lowest Rated Tourist Attractions')
plt.xlabel('Tourist Attraction')
plt.ylabel('Average Rating')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Analisis Jaringan Sosial (Social Network Analysis - SNA)

### STEP 1. Gabungkan semua review per tempat
"""

import pandas as pd
import re

def clean_text(text):
    text=str(text)
    text=text.lower()
    text=re.sub(r"http\S+","",text)
    text=re.sub(r"[^a-zA-Z\s]","",text)
    text=re.sub(r"\s+"," ",text) # Corrected: removed the extra empty string argument
    return text.strip()

def label_rating(r):
    if r==5:
        return "Puas"
    elif r<=2:
        return "Kecewa"
    else:
        return None

# Re-initialize and clean df to ensure all columns are present
df = pd.DataFrame(all_data)
df["clean_comment"] = df["comment"].apply(clean_text)
df["label"] = df["rating"].apply(label_rating)
df = df.dropna()

place_text = df.groupby("place")["clean_comment"]\
               .apply(lambda x: " ".join(x))

print(place_text.head())

"""### STEP 2. Ubah menjadi TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(place_text)
print("TF-IDF matrix shape:", X.shape)

"""### STEP 3. Hitung kemiripan antar tempat (Cosine Similarity)"""

from sklearn.metrics.pairwise import cosine_similarity

sim = cosine_similarity(X)

# Display a part of the similarity matrix
print(sim[:5, :5])

"""### STEP 4. Buat graph SNA
### STEP 5. Tambahkan node
"""

import networkx as nx

G = nx.Graph()

places = place_text.index

for p in places:
    G.add_node(p)

print(f"Graph created with {G.number_of_nodes()} nodes.")

"""### STEP 6. Tambahkan edge"""

threshold = 0.2

for i in range(len(places)):
    for j in range(i + 1, len(places)):
        if sim[i, j] > threshold:
            G.add_edge(
                places[i],
                places[j],
                weight=sim[i, j]
            )
print(f"Graph now has {G.number_of_edges()} edges with similarity above {threshold}.")

"""### STEP 7. Visualisasi Graph SNA"""

import matplotlib.pyplot as plt

plt.figure(figsize=(15, 10)) # Increased figure size for better readability

pos = nx.spring_layout(G, seed=42, k=0.7) # Adjusted k parameter for better spacing

nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=5000, # Increased node size
    font_size=9,    # Adjusted font size
    font_weight='bold',
    edge_color='gray',
    alpha=0.7
)

# Draw edge labels (weights)
edges = G.edges(data=True)
edge_labels = {(u, v): f'{d["weight"]:.2f}' for u, v, d in edges}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8, font_color='red')

plt.title('Social Network Analysis of Tourist Attractions based on Review Similarity', size=15)
plt.show()

"""### STEP 8. Tampilkan bobot hubungan (Edge Weights)"""

print("Bobot hubungan (Similarity) antar tempat wisata:")
for u, v, w in G.edges(data=True):
    print(
        u,
        "<->",
        v,
        "Similarity:",
        round(w["weight"], 3)
    )

"""Untuk menjalankan aplikasi Streamlit ini, Anda perlu menyimpan kode di bawah ini ke dalam file `.py` (misalnya, `app.py`) di komputer Anda. Pastikan file `wisata_dataset.csv` dan `hasil_akhir_wisata.csv` berada di direktori yang sama, atau Anda dapat menyesuaikan jalur file. Anda juga harus memiliki file `requirements.txt` seperti yang telah dibahas sebelumnya.

Kemudian, buka terminal atau command prompt, navigasikan ke direktori tempat Anda menyimpan file tersebut, dan jalankan perintah:

```bash
streamlit run app.py
```
"""

# Instal paket yang diperlukan untuk menjalankan di Colab
# Untuk deployment Streamlit, gunakan requirements.txt
!pip install streamlit requests

import streamlit as st
import pandas as pd
import re
import networkx as nx
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import seaborn as sns
import os

# --- Konfigurasi Streamlit ---
st.set_page_config(layout="wide")
st.title("Analisis Sentimen dan Jaringan Sosial Tempat Wisata") # Judul disederhanakan untuk menghindari UnicodeEncodeError
st.markdown("Dashboard ini menyajikan analisis ulasan tempat wisata, mulai dari sentimen, klustering, hingga keterkaitan antar tempat.")

# --- API Key (gunakan st.secrets untuk deployment yang aman) ---
# Untuk contoh ini, kita hardcode. Untuk produksi, gunakan st.secrets
API_KEY = "AIzaSyDYP-2xVmDPdcyHZ6si_eypeQhP4l7WBag"

# --- Fungsi Preprocessing ---
def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def label_rating(r):
    if r == 5:
        return "Puas"
    elif r <= 2:
        return "Kecewa"
    else:
        return None

# --- Fungsi Pengambilan Data dari Google Places API (Cached) ---
@st.cache_data
def get_place_id(query):
    url = "https://maps.googleapis.com/maps/api/place/textsearch/json"
    params = {
        "query": query,
        "key": API_KEY
    }
    res = requests.get(url, params=params)
    data = res.json()
    if data and data.get("results"):
        return data["results"][0]["place_id"]
    return None

@st.cache_data
def get_reviews(place_id, place_name):
    url = "https://maps.googleapis.com/maps/api/place/details/json"
    params = {
        "place_id": place_id,
        "fields": "name,rating,reviews",
        "key": API_KEY
    }
    res = requests.get(url, params=params)
    data = res.json()
    reviews = []
    for r in data.get("result", {}).get("reviews", []):
        reviews.append({
            "place": place_name,
            "rating": r.get("rating"),
            "comment": r.get("text")
        })
    return reviews

@st.cache_data
def fetch_and_process_data(places_list):
    all_data = []
    for p in places_list:
        pid = get_place_id(p)
        if pid:
            review = get_reviews(pid, p)
            all_data.extend(review)

    df = pd.DataFrame(all_data)
    df["clean_comment"] = df["comment"].apply(clean_text)
    df["label"] = df["rating"].apply(label_rating)
    df = df.dropna()
    return df

# --- Data Loading (Prioritaskan file CSV yang sudah ada) ---
DATA_FILE = "hasil_akhir_wisata.csv"
if os.path.exists(DATA_FILE):
    df = pd.read_csv(DATA_FILE)
    st.success(f"Data berhasil dimuat dari {DATA_FILE}")
    df["clean_comment"] = df["comment"].apply(clean_text) # Ensure clean_comment exists
    df["label"] = df["rating"].apply(label_rating) # Ensure label exists
    df = df.dropna()
else:
    st.warning(f"File {DATA_FILE} tidak ditemukan. Memulai pengambilan data dari Google Places API (ini mungkin membutuhkan waktu).")
    places = [
        "Candi Borobudur", "Candi Prambanan", "Gunung Bromo", "Malioboro",
        "Raja Ampat", "Labuan Bajo", "Danau Toba", "Pantai Kuta Bali",
        "Pantai Parangtritis", "Kawah Ijen", "Monas Jakarta",
        "Taman Mini Indonesia Indah", "Tangkuban Perahu", "Pantai Sanur Bali",
        "Bali Zoo", "Jatim Park 1", "Jatim Park 2", "Museum Angkut",
        "Pantai Pangandaran", "Kebun Raya Bogor"
    ]
    with st.spinner("Mengambil data ulasan dari Google Places API..."):
        df = fetch_and_process_data(places)
        if not df.empty:
            df.to_csv(DATA_FILE, index=False)
            st.success("Data berhasil diambil dan disimpan.")
        else:
            st.error("Gagal mengambil data. Pastikan API_KEY valid dan ada koneksi internet.")
            st.stop()


if not df.empty:
    st.subheader("Sekilas Data Ulasan")
    st.dataframe(df.head())
    st.write(f"Total Ulasan yang Diproses: {len(df)}")
    st.write(f"Kolom Data: {df.columns.tolist()}")

    # --- Analisis Sentimen (Logistic Regression) ---
    st.subheader("Analisis Sentimen")
    with st.spinner("Melakukan analisis sentimen..."):
        tfidf_sentiment = TfidfVectorizer()
        X_sentiment = tfidf_sentiment.fit_transform(df["clean_comment"])
        y_sentiment = df["label"]

        X_train, X_test, y_train, y_test = train_test_split(
            X_sentiment,
            y_sentiment,
            test_size=0.2,
            random_state=42
        )

        model_sentiment = LogisticRegression(max_iter=1000) # Increased max_iter for convergence
        model_sentiment.fit(X_train, y_train)
        st.info(f"Akurasi Model Sentimen (Logistic Regression) pada data uji: **{model_sentiment.score(X_test, y_test):.2f}**")

    # --- Klustering (KMeans) ---
    st.subheader("Klustering Ulasan")
    n_clusters = st.slider("Pilih Jumlah Kluster untuk KMeans", min_value=2, max_value=10, value=3)
    with st.spinner(f"Melakukan klustering dengan {n_clusters} kluster..."):
        kmeans = KMeans(
            n_clusters=n_clusters,
            random_state=42,
            n_init=10 # Added n_init to suppress warning
        )
        cluster = kmeans.fit_predict(X_sentiment) # Using the same TF-IDF matrix
        df["cluster"] = cluster
        st.dataframe(df[["place", "clean_comment", "cluster"]].head())
        st.write("Distribusi Kluster:")
        st.bar_chart(df["cluster"].value_counts())

    # --- Word Cloud ---
    st.subheader("Word Cloud dari Ulasan")
    all_words = " ".join(df["clean_comment"])
    if all_words:
        wc = WordCloud(
            width=800,
            height=400,
            background_color='white'
        ).generate(all_words)
        fig_wc, ax_wc = plt.subplots(figsize=(12, 6))
        ax_wc.imshow(wc, interpolation='bilinear')
        ax_wc.axis("off")
        st.pyplot(fig_wc)
    else:
        st.warning("Tidak ada teks untuk membuat Word Cloud.")

    # --- Analisis Rating Tempat Wisata ---
    st.subheader("Analisis Rating Tempat Wisata")
    avg_ratings = df.groupby('place')['rating'].mean().sort_values(ascending=False)
    top_5_places = avg_ratings.head(5)
    bottom_5_places = avg_ratings.tail(5).sort_values(ascending=True)
    plot_data = pd.concat([top_5_places, bottom_5_places])

    fig_rating, ax_rating = plt.subplots(figsize=(12, 6))
    sns.barplot(x=plot_data.index, y=plot_data.values, palette='viridis', ax=ax_rating)
    ax_rating.set_title('Top 5 Highest and Lowest Rated Tourist Attractions')
    ax_rating.set_xlabel('Tourist Attraction')
    ax_rating.set_ylabel('Average Rating')
    ax_rating.tick_params(axis='x', rotation=45) # Removed ha='right'
    fig_rating.tight_layout()
    st.pyplot(fig_rating)

    # --- Analisis Jaringan Sosial (SNA) ---
    st.subheader("Analisis Jaringan Sosial (SNA)")
    st.markdown("Memvisualisasikan kemiripan antar tempat wisata berdasarkan ulasan.")

    with st.spinner("Membangun dan memvisualisasikan grafik SNA..."):
        place_text = df.groupby("place")["clean_comment"].apply(lambda x: " ".join(x))
        tfidf_sna = TfidfVectorizer()
        X_sna = tfidf_sna.fit_transform(place_text)
        sim = cosine_similarity(X_sna)

        G = nx.Graph()
        places_sna = place_text.index
        for p in places_sna:
            G.add_node(p)

        threshold = st.slider("Pilih Ambang Batas Kemiripan untuk Edge", min_value=0.0, max_value=0.5, value=0.2, step=0.05)
        for i in range(len(places_sna)):
            for j in range(i + 1, len(places_sna)):
                if sim[i, j] > threshold:
                    G.add_edge(
                        places_sna[i],
                        places_sna[j],
                        weight=sim[i, j]
                    )

        if G.number_of_edges() > 0:
            fig_sna, ax_sna = plt.subplots(figsize=(15, 10))
            pos = nx.spring_layout(G, seed=42, k=0.7)

            nx.draw(
                G,
                pos,
                with_labels=True,
                node_size=5000,
                font_size=9,
                font_weight='bold',
                edge_color='gray',
                alpha=0.7,
                ax=ax_sna
            )

            edges = G.edges(data=True)
            edge_labels = {(u, v): f'{d["weight"]:.2f}' for u, v, d in edges}
            nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8, font_color='red', ax=ax_sna)

            ax_sna.set_title(f'Social Network Analysis of Tourist Attractions (Similarity > {threshold})', size=15)
            st.pyplot(fig_sna)

            st.subheader("Bobot Hubungan (Similarity) Antar Tempat Wisata")
            for u, v, w in G.edges(data=True):
                st.write(f"- {u} <-> {v}: Similarity = {w['weight']:.3f}")
        else:
            st.warning(f"Tidak ada hubungan antar tempat wisata dengan ambang batas kemiripan di atas {threshold}.")
else:
    st.error("Tidak ada data yang tersedia untuk analisis.")